spring:
  datasource:
    url: jdbc:mariadb://hospidata-db:3306/notification_schema
    username: hospidata-user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080

  kafka:
    bootstrap-servers: hospidata-kafka:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'br.com.hospidata.notification_service.dto.**'
        spring.json.value.default.type: 'br.com.hospidata.notification_service.dto.AppointmentNotification'
    listener:
      ack-mode: record