FROM maven:3.9-eclipse-temurin-21-alpine AS builder

WORKDIR /build
COPY ./appointment-service/pom.xml ./
COPY ./appointment-service/src ./src
RUN mvn clean install -DskipTests

FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app
COPY --from=builder /build/target/appointment-service-1.0.0.jar app.jar

# copia o .env pro container
COPY .env ./

RUN mkdir -p /app/logs

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]