version: "3.8"

services:

  gateway-service:
    build:
      dockerfile: Dockerfile.gateway-service
    container_name: gateway-service
    env_file:
      - .env-gateway
    ports:
      - "8080:8080"
    networks:
      - hospidata-network
    restart: always
    depends_on:
      hospidata-db:
        condition: service_healthy

  history-service:
    build:
      dockerfile: Dockerfile.history-service
    container_name: history-service
    env_file:
      - .env-history
#    ports:
#      - "8081:8080"
    networks:
      - hospidata-network
    restart: always
    depends_on:
      hospidata-db:
        condition: service_healthy

  appointment-service:
    build:
      dockerfile: Dockerfile.appointment-service
    container_name: appointment-service
    env_file:
      - .env-appointment
#    ports:
#      - "8082:8080"
    networks:
      - hospidata-network
    restart: always
    depends_on:
      hospidata-db:
        condition: service_healthy

  notification-service:
    build:
      dockerfile: Dockerfile.notification-service
    container_name: notification-service
    env_file:
      - .env-notification
    networks:
      - hospidata-network
    restart: always
    depends_on:
      hospidata-db:
        condition: service_healthy
      hospidata-kafka:
        condition: service_started

  hospidata-kafka:
    build:
      dockerfile: Dockerfile.hospidata-kafka
    container_name: hospidata-kafka
    env_file:
      - .env
#    ports:
#      - "9092:9092"
#      - "9093:9093"
#      - "9094:9094"
    volumes:
      - kafka_hd_data:/bitnami/kafka
    networks:
      - hospidata-network
    restart: always

  hospidata-db:
    build:
      dockerfile: Dockerfile.hospidata-db
    container_name: hospidata-db
    env_file:
      - .env
#    ports:
#      - "3306:3306"
    volumes:
      - mariadb_hd_data:/var/lib/mysql
    networks:
      - hospidata-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mariadb_hd_data:
  kafka_hd_data:

networks:
  hospidata-network:
    driver: bridge