spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/main_schema
    username: hospidata-user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
