spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/main_schema
    username: hospidata-user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect

  jwt:
    secret: b6b096c3-e08f-40dd-b1f3-f8ff1711ec6e
    access-token-validity: 900000
    refresh-token-validity: 604800000

clients:
  appointment-service:
    url: http://appointment-service:8080
  history-service:
    url: http://history-service:8080
