spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/appointment_schema
    username: hospidata-user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  kafka:
    bootstrap-servers: hospidata-kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect